/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=MemoryBindings src/bindings.d.ts` (hash: 18e2505ef04db0de82ce5a5deb90c76d)
interface __BaseEnv_MemoryBindings {
	OAUTH_KV: KVNamespace;
	DB: D1Database;
	ASSETS: Fetcher;
	SESSION_SECRET: string;
	APP_ORIGIN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_MemoryBindings {}
}
interface MemoryBindings extends __BaseEnv_MemoryBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SESSION_SECRET" | "APP_ORIGIN">> {}
}
